### PR TITLE
resolved issue with servlet configuration

### PR DESCRIPTION
**Pull request by satyayalamanchi**

### CODE REVIEW

**Comment by satyayalamanchi** [comment]
i ve checked out release1.

but the "deployment assembly" in release1 doesnt contain lib.  "deployment
assembly" in login_changes contain lib

how to add lib folder in "deployment assembly"

On Mon, Jan 26, 2015 at 8:46 PM, ramesh sunkari <notifications@github.com>
wrote:

> Merged #3 <https://github.com/satyayalamanchi/Gems1/pull/3>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/satyayalamanchi/Gems1/pull/3#event-224681789>.
>



-- 
Yalamanchi Satya

**Comment by satyayalamanchi** [comment]
there is a lib folder in login_changes but not in release1

On Tue, Jan 27, 2015 at 10:51 AM, Satya Yalamanchi <
yalamanchisatya@gmail.com> wrote:

> i ve checked out release1.
>
> but the "deployment assembly" in release1 doesnt contain lib.  "deployment
> assembly" in login_changes contain lib
>
> how to add lib folder in "deployment assembly"
>
> On Mon, Jan 26, 2015 at 8:46 PM, ramesh sunkari <notifications@github.com>
> wrote:
>
>> Merged #3 <https://github.com/satyayalamanchi/Gems1/pull/3>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/satyayalamanchi/Gems1/pull/3#event-224681789>.
>>
>
>
>
> --
> Yalamanchi Satya
>



-- 
Yalamanchi Satya

**Comment by rameshsunkari** [comment]
https://github.com/satyayalamanchi/Gems1/tree/Release1/GEMS

the release1 has the lib folder...

you have to pull the changes to your local branch..

Thanks,
Ramesh

**Comment by satyayalamanchi** [comment]
i just need to talk 2 u for a minute regarding other issue. attend my call

On Tue, Jan 27, 2015 at 12:25 PM, ramesh sunkari <notifications@github.com>
wrote:

> https://github.com/satyayalamanchi/Gems1/tree/Release1/GEMS
>
> the release1 has the lib folder...
>
> you have to pull the changes to your local branch..
>
> Thanks,
> Ramesh
>
> On Tue, Jan 27, 2015 at 11:01 AM, satyayalamanchi <
> notifications@github.com>
> wrote:
>
> > there is a lib folder in login_changes but not in release1
> >
> > On Tue, Jan 27, 2015 at 10:51 AM, Satya Yalamanchi <
> > yalamanchisatya@gmail.com> wrote:
> >
> > > i ve checked out release1.
> > >
> > > but the "deployment assembly" in release1 doesnt contain lib.
> > "deployment
> > > assembly" in login_changes contain lib
> > >
> > > how to add lib folder in "deployment assembly"
> > >
> > > On Mon, Jan 26, 2015 at 8:46 PM, ramesh sunkari <
> > notifications@github.com>
> > > wrote:
> > >
> > >> Merged #3 <https://github.com/satyayalamanchi/Gems1/pull/3>.
> > >>
> > >> --
> > >> Reply to this email directly or view it on GitHub
> > >> <https://github.com/satyayalamanchi/Gems1/pull/3#event-224681789>.
> > >>
> > >
> > >
> > >
> > > --
> > > Yalamanchi Satya
> > >
> >
> >
> >
> > --
> > Yalamanchi Satya
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <https://github.com/satyayalamanchi/Gems1/pull/3#issuecomment-71591998>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/satyayalamanchi/Gems1/pull/3#issuecomment-71598124>.
>



-- 
Yalamanchi Satya

**Comment by rameshsunkari** [comment]
one another call will call you after that


Thanks,
Ramesh

**Comment by satyayalamanchi** [comment]
ok

On Tue, Jan 27, 2015 at 12:27 PM, ramesh sunkari <notifications@github.com>
wrote:

> one another call will call you after that
>
>
> Thanks,
> Ramesh
>
> On Tue, Jan 27, 2015 at 12:27 PM, satyayalamanchi <
> notifications@github.com>
> wrote:
>
>
> > i just need to talk 2 u for a minute regarding other issue. attend my
> call
> >
> > On Tue, Jan 27, 2015 at 12:25 PM, ramesh sunkari <
> notifications@github.com>
> >
> > wrote:
> >
> > > https://github.com/satyayalamanchi/Gems1/tree/Release1/GEMS
> > >
> > > the release1 has the lib folder...
> > >
> > > you have to pull the changes to your local branch..
> > >
> > > Thanks,
> > > Ramesh
> > >
> > > On Tue, Jan 27, 2015 at 11:01 AM, satyayalamanchi <
> > > notifications@github.com>
> > > wrote:
> > >
> > > > there is a lib folder in login_changes but not in release1
> > > >
> > > > On Tue, Jan 27, 2015 at 10:51 AM, Satya Yalamanchi <
> > > > yalamanchisatya@gmail.com> wrote:
> > > >
> > > > > i ve checked out release1.
> > > > >
> > > > > but the "deployment assembly" in release1 doesnt contain lib.
> > > > "deployment
> > > > > assembly" in login_changes contain lib
> > > > >
> > > > > how to add lib folder in "deployment assembly"
> > > > >
> > > > > On Mon, Jan 26, 2015 at 8:46 PM, ramesh sunkari <
> > > > notifications@github.com>
> > > > > wrote:
> > > > >
> > > > >> Merged #3 <https://github.com/satyayalamanchi/Gems1/pull/3>.
> > > > >>
> > > > >> --
> > > > >> Reply to this email directly or view it on GitHub
> > > > >> <https://github.com/satyayalamanchi/Gems1/pull/3#event-224681789
> >.
> > > > >>
> > > > >
> > > > >
> > > > >
> > > > > --
> > > > > Yalamanchi Satya
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Yalamanchi Satya
> > > >
> > > > --
> > > > Reply to this email directly or view it on GitHub
> > > > <
> https://github.com/satyayalamanchi/Gems1/pull/3#issuecomment-71591998>.
> >
> > >
> > > >
> > >
> > > --
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/satyayalamanchi/Gems1/pull/3#issuecomment-71598124
> >.
> >
> > >
> >
> >
> >
> > --
> > Yalamanchi Satya
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <https://github.com/satyayalamanchi/Gems1/pull/3#issuecomment-71598224>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/satyayalamanchi/Gems1/pull/3#issuecomment-71598289>.
>



-- 
Yalamanchi Satya

**Comment by satyayalamanchi** [comment]
this is the deployment assembly in resource1. look at the left side in
project explorer, we cant find lib folder

[image: Inline image 1]

this is the deployment assembly in login changes. look at the left side in
project explorer, there is lib folder

[image: Inline image 2]

On Tue, Jan 27, 2015 at 12:28 PM, Satya Yalamanchi <
yalamanchisatya@gmail.com> wrote:

> ok
>
> On Tue, Jan 27, 2015 at 12:27 PM, ramesh sunkari <notifications@github.com
> > wrote:
>
>> one another call will call you after that
>>
>>
>> Thanks,
>> Ramesh
>>
>> On Tue, Jan 27, 2015 at 12:27 PM, satyayalamanchi <
>> notifications@github.com>
>> wrote:
>>
>>
>> > i just need to talk 2 u for a minute regarding other issue. attend my
>> call
>> >
>> > On Tue, Jan 27, 2015 at 12:25 PM, ramesh sunkari <
>> notifications@github.com>
>> >
>> > wrote:
>> >
>> > > https://github.com/satyayalamanchi/Gems1/tree/Release1/GEMS
>> > >
>> > > the release1 has the lib folder...
>> > >
>> > > you have to pull the changes to your local branch..
>> > >
>> > > Thanks,
>> > > Ramesh
>> > >
>> > > On Tue, Jan 27, 2015 at 11:01 AM, satyayalamanchi <
>> > > notifications@github.com>
>> > > wrote:
>> > >
>> > > > there is a lib folder in login_changes but not in release1
>> > > >
>> > > > On Tue, Jan 27, 2015 at 10:51 AM, Satya Yalamanchi <
>> > > > yalamanchisatya@gmail.com> wrote:
>> > > >
>> > > > > i ve checked out release1.
>> > > > >
>> > > > > but the "deployment assembly" in release1 doesnt contain lib.
>> > > > "deployment
>> > > > > assembly" in login_changes contain lib
>> > > > >
>> > > > > how to add lib folder in "deployment assembly"
>> > > > >
>> > > > > On Mon, Jan 26, 2015 at 8:46 PM, ramesh sunkari <
>> > > > notifications@github.com>
>> > > > > wrote:
>> > > > >
>> > > > >> Merged #3 <https://github.com/satyayalamanchi/Gems1/pull/3>.
>> > > > >>
>> > > > >> --
>> > > > >> Reply to this email directly or view it on GitHub
>> > > > >> <https://github.com/satyayalamanchi/Gems1/pull/3#event-224681789
>> >.
>> > > > >>
>> > > > >
>> > > > >
>> > > > >
>> > > > > --
>> > > > > Yalamanchi Satya
>> > > > >
>> > > >
>> > > >
>> > > >
>> > > > --
>> > > > Yalamanchi Satya
>> > > >
>> > > > --
>> > > > Reply to this email directly or view it on GitHub
>> > > > <
>> https://github.com/satyayalamanchi/Gems1/pull/3#issuecomment-71591998>.
>> >
>> > >
>> > > >
>> > >
>> > > --
>> > > Reply to this email directly or view it on GitHub
>> > > <
>> https://github.com/satyayalamanchi/Gems1/pull/3#issuecomment-71598124>.
>> >
>> > >
>> >
>> >
>> >
>> > --
>> > Yalamanchi Satya
>> >
>> > --
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/satyayalamanchi/Gems1/pull/3#issuecomment-71598224
>> >.
>>
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/satyayalamanchi/Gems1/pull/3#issuecomment-71598289>.
>>
>
>
>
> --
> Yalamanchi Satya
>



-- 
Yalamanchi Satya

**Pull request merged**
